---

- name: Patch for old Mojave versions
  block:
    - name: Get active developer directory
      command: xcode-select -p
      register: xcode_select_path
      changed_when: false

    # yamllint disable rule:line-length
    - name: Check if we're using Command Line Tools
      set_fact:
        macos_clt: "{{ xcode_select_path.stdout == '/Library/Developer/CommandLineTools' }}"
    # yamllint enable rule:line-length

    - name: Get macOS version
      set_fact:
        macos_version: "{{ ansible_distribution_version |
                        regex_search('^([0-9]+\\.[0-9]+)') }}"

    - name: macOS Mojave setup
      include_tasks: "Mojave.yml"
      when: macos_version == "10.14" and not macos_clt

  when: pyenv_macos_mojave_patch | bool

- name: Install pyenv build requirements with Homebrew
  homebrew:
    name: "{{ pyenv_build_requirements }}"

- name: Detect existing pyenv install
  include_tasks: detect_existing_install.yml
  when: pyenv_detect_existing_install|bool

- name: Install with Homebrew
  include_tasks: install_with_homebrew.yml
  when: pyenv_install_from_package_manager|bool

- name: Uninstall Homebrew packages
  include_tasks: remove_homebrew.yml
  when: not pyenv_install_from_package_manager|bool

- name: Install with Git
  include_tasks: install_with_git.yml
  when: not pyenv_install_from_package_manager|bool
