---

- name: Make sure .pyenv directory exists
  file:
    path: "{{ pyenv_root }}"
    state: directory

- name: Make sure WORKON_HOME directory exists
  file:
    path: "{{ pyenv_virtualenvwrapper_home }}"
    state: directory
  when: pyenv_virtualenvwrapper|bool

- name: Create .pyenvrc
  template:
    src: ".pyenvrc.j2"
    dest: "{{ pyenv_root }}/.pyenvrc"
    mode: "0644"
