---
- name: Update APT cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Remove Initial Setup
  package:
    name: gnome-initial-setup
    state: absent

- name: Remove VBoxGuestAdditions.iso
  file:
    path: /home/vagrant/VBoxGuestAdditions.iso
    state: absent

- name: Check if there are available updates
  command: /usr/lib/update-notifier/apt-check --package-names
  register: pkg_list

- name: Perform upgrade of all packages to the latest version
  apt:
    upgrade: dist
  when: pkg_list.stderr != ""

# - name: Check if a reboot is required
#   stat: path=/var/run/reboot-required get_md5=no
#   register: reboot_flag

# - name: Reboot the server is needed
#   reboot:
#     reboot_timeout: 300
#   when: reboot_flag.stat.exists == true

# - debug:
#     msg: "Server is back up and running"

- name: Add official Docker APT repository (Ubuntu)
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu disco stable"
    state: present
    filename: "docker-official"
    update_cache: yes

- name: Install Docker Compose
  shell: curl -L https://github.com/docker/compose/releases/download/1.25.0/docker-compose-Linux-x86_64 > /usr/local/bin/docker-compose
  args:
    creates: /usr/local/bin/docker-compose

- name: Apply executable permissions to docker-compose
  file: path=/usr/local/bin/docker-compose state=file mode=0755

- name: Add users to the Docker group
  user:
    name: vagrant
    groups: docker
    append: yes

# always try to use HTTPS. I'm not sure why the nginx folks don't provide it.
- name: add google-cloud-sdk apt-key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
    keyring: /usr/share/keyrings/cloud.google.gpg

- name: add google-cloud-sdk apt repository
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main"
    state: present
    update_cache: yes

- name: install google-cloud-sdk
  apt:
    name: google-cloud-sdk
    state: present
    update_cache: yes
